# Generated by Django 5.0.4 on 2024-07-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsgoToursAndTravels', '0002_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LetsgoToursAndTravels.places'),
            preserve_default=False,
        ),
    ]
