# Generated by Django 5.0.4 on 2024-07-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsgoToursAndTravels', '0003_tour_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencies',
            name='Tours_available',
            field=models.ManyToManyField(to='LetsgoToursAndTravels.tour', verbose_name='Tours Available'),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Agency Name'),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='representative',
            field=models.CharField(max_length=100, verbose_name='Representative'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure',
            field=models.DateTimeField(verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tour Name'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsgoToursAndTravels.places', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
