# Generated by Django 5.0.7 on 2024-07-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsgoToursAndTravels', '0004_alter_agencies_tours_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_tour/', verbose_name='Image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsgoToursAndTravels.places', verbose_name='Place')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsgoToursAndTravels.tour', verbose_name='Tour_Name')),
            ],
        ),
    ]
