# Generated by Django 5.0.7 on 2024-07-25 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsgoToursAndTravels', '0005_pictures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('insurance', models.BooleanField(verbose_name='Travel Insurance')),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsgoToursAndTravels.tour', verbose_name='Tour')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
